### ISSUE TITLE
[Suggestion] Piazza Course

### ISSUE THREAD

**Issue by gondek** [midvalestudent/Math307JanApr2016#1]
Would it be possible to create a [Piazza](https://piazza.com/) course for MATH 307? In my past math courses my classmates and I have found it to be a valuable resource and it also reduced the number of questions the instructor had to answer on an individual basis.

Thanks!

**Comment by midvalestudent** [comment]
Done:  good suggestion -- [sign up](piazza.com/ubc.ca/winterterm22015/sisubcmath3072022015w261015)

**Comment by gondek** [comment]
Thank you!

Could the class title be changed to MATH 307 from the default Connect title? It could help students find the class easier.

**Comment by midvalestudent** [comment]
I think I'll leave it as is so that the instructor of the other class (section 201) can also make a page if they want to without a name conflict -- besides, the search box in the student signup page of Piazza seems to auto-fill if for some reason students don't just follow the link from this page
